
[34m[1mtrain: [39m[22mScanning C:\Studium\Semester5\DSPRO2\DSPOR2\classifier\Model\datasets\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 128/128 [00:00<?, ?it/s]
[34m[1mval: [39m[22mScanning C:\Studium\Semester5\DSPRO2\DSPOR2\classifier\Model\datasets\coco128\labels\train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 128/128 [00:00<?, ?it/s]
  0%|          | 0/8 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\sral0\AppData\Local\Temp\ipykernel_21228\3308013378.py", line 10, in <module>
    model.train(project="DSPRO2", data="coco128.yaml", epochs=1, imgsz=640)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\engine\model.py", line 667, in train
    self.trainer.train()
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\engine\trainer.py", line 213, in train
    self._do_train(world_size)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\engine\trainer.py", line 381, in _do_train
    self.loss, self.loss_items = self.model(batch)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\tasks.py", line 88, in forward
    return self.loss(x, *args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\tasks.py", line 266, in loss
    preds = self.forward(batch["img"]) if preds is None else preds
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\tasks.py", line 89, in forward
    return self.predict(x, *args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\tasks.py", line 107, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\tasks.py", line 128, in _predict_once
    x = m(x)  # run
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\modules\block.py", line 229, in forward
    y = list(self.cv1(x).chunk(2, 1))
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\ultralytics\nn\modules\conv.py", line 50, in forward
    return self.act(self.bn(self.conv(x)))
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\modules\activation.py", line 393, in forward
    return F.silu(input, inplace=self.inplace)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\torch\nn\functional.py", line 2074, in silu
    return torch._C._nn.silu_(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 6.00 GiB of which 2.83 GiB is free. Of the allocated memory 1.05 GiB is allocated by PyTorch, and 40.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\interactiveshell.py", line 2168, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\ultratb.py", line 1454, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\ultratb.py", line 1345, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\ultratb.py", line 1192, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\ultratb.py", line 1082, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\IPython\core\ultratb.py", line 1179, in get_records
    res = list(stack_data.FrameInfo.stack_data(etb, options=options))[tb_offset:]
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\stack_data\core.py", line 597, in stack_data
    yield from collapse_repeated(
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\stack_data\utils.py", line 83, in collapse_repeated
    yield from map(mapper, original_group)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\stack_data\core.py", line 587, in mapper
    return cls(f, options)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\stack_data\core.py", line 551, in __init__
    self.executing = Source.executing(frame_or_tb)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\executing\executing.py", line 264, in executing
    source = cls.for_frame(frame)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\executing\executing.py", line 183, in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\executing\executing.py", line 212, in for_filename
    return cls._for_filename_and_lines(filename, tuple(lines))
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\executing\executing.py", line 223, in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
  File "C:\Studium\Semester5\DSPRO2\venv2\lib\site-packages\executing\executing.py", line 163, in __init__
    self.tree = ast.parse(self.text, filename=filename)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
MemoryError
Unexpected exception formatting exception. Falling back to standard exception
<xml><var name="_dummy_ipython_val"  />
<var name="_dummy_special_var"  />
<var name="item" type="str" qualifier="builtins" value="diacritics.yaml" />
<var name="item_path" type="str" qualifier="builtins" value="datasets/diacritics/diacritics.yaml" />
<var name="model" type="YOLO" qualifier="ultralytics.models.yolo.model" value="YOLO%28%0A  %28model%29%3A DetectionModel%28%0A    %28model%29%3A Sequential%28%0A      %280%29%3A Conv%28%0A        %28conv%29%3A Conv2d%283%2C 16%2C kernel_size=%283%2C 3%29%2C s...       %28dfl%29%3A DFL%28%0A          %28conv%29%3A Conv2d%2816%2C 1%2C kernel_size=%281%2C 1%29%2C stride=%281%2C 1%29%2C bias=False%29%0A        %29%0A      %29%0A    %29%0A  %29%0A%29" isContainer="True" />
<var name="output" type="str" qualifier="builtins" value="datasets/diacritics/" />
<var name="url" type="str" qualifier="builtins" value="https%3A//drive.google.com/drive/folders/1ZgyaiR2i-YDoZSafAA66wM96PkyKkypK%3Fusp=sharing" />
</xml>
